service: cloudfront-invalidate-dist

provider:
  name: aws
  runtime: ${opt:runtime, 'nodejs12.x'}
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "codepipeline:PutJobFailureResult"
        - "codepipeline:PutJobSuccessResult"
        - "cloudfront:CreateInvalidation"
      Resource: "*"

functions:
  invalidate-via-code:
    handler: cloudfront-invalidate-via-code/handler.handler

  invalidate-via-pipeline:
    handler: cloudfront-invalidate-via-pipeline/handler.handler
